### ISSUE TITLE
Results should better use a formatted output

### ISSUE THREAD

**Issue by reklawykSekuL** [pcboy/g81_relative#12]
first thanks for your great tool.
I used your great feature site [https://pcboy.github.io/g81_relative/](url)  to analyze my iMK3S bed leveling.
With my last(best) values the output of the results is a little disturbed (see attached jpg).
Maybe a fixed formatting of the values gives a nicer result view.  -02.3 for the mm Values   -3.0 for the angle values 

`SENDING:G81
Num X,Y: 7,7
Z search height: 5.00
Measured points:
  0.14250  0.08500  0.12850  0.13100  0.15300  0.13700  0.14200
  0.10700  0.10550  0.09850  0.08200  0.11800  0.13050  0.07400
  0.12750  0.13400  0.13050  0.12287  0.14050  0.14600  0.08300
  0.11950  0.11850  0.10650  0.13850  0.14812  0.13650  0.09050
  0.13000  0.14100  0.14650  0.15538  0.17700  0.18500  0.11150
  0.13100  0.15000  0.15800  0.15950  0.18500  0.18950  0.12400
  0.13950  0.14850  0.15550  0.15950  0.17500  0.16650  0.11900
`
best regards
Luke

![Convert_g81_Format](https://user-images.githubusercontent.com/25550681/105611408-6f239a00-5db5-11eb-93a6-80c516d23257.jpg)

**Comment by pcboy** [comment]
Hello Luke,

Indeed that looks like crap.  
Thing is, the output is simply in an html `<input>` so the formatting is limited (it's technically the result of a ruby script, originally g81_relative was a simple CLI tool, I just made the web page because people asked for it).  
But I can clearly make it better by simply being sure to have always 2 decimals for the raw values. That's why it's messed up right now, because you have a 0 instead of 0.00.

I made some changes here for that (not merged yet):  
https://github.com/pcboy/g81_relative/pull/13  

Screenshot of the result:  
![image](https://user-images.githubusercontent.com/943430/105619650-38db2e80-5e38-11eb-932d-289989e5bf06.png)

Can you confirm me that this output would be suitable? It sounds ok to me.

EDIT:  
Ideally, I guess the ruby script could also have another function to return a JSON object that the web UI could use and then we could improve the format. That's a thing I can do but takes a bit of time, will see if I can find the time next week. The #13 PR could still be merged for now as a workaround.

**Comment by reklawykSekuL** [comment]
hey that looks good, and is absolutly suitable to me.
it has helped me to level my iMK3s heatbed really flat.

Best regards
Luke
