### ISSUE TITLE
Stops working when refreshed

### ISSUE THREAD

**Issue by haarp** [pcboy/g81_relative#8]
Great tool, thanks for making this!

Unfortunately there's a bug that cost me half a day of debugging. When the site is refreshed after data had already been entered, it will stop updating entirely. And since there's no refresh indicator, I didn't notice that the output data was stale, and I ended up screwing up the heatbed enough for the printer to go crazy with enforced Z calibration :(

Cheers

**Comment by pcboy** [comment]
Hi,

I can't reproduce this issue and fail to understand how that could happen. I must be missing some information.  
When you refresh the page the 2 input boxes should be reset and empty (beside the placeholder text). Do you happen to have a chrome extension saving these inputs maybe?  
Also, every time you change anything in the first input box, the second input box should be refreshed anyway (unless maybe if you get an actual error in the calculation, could you maybe give me the input values you entered?).  
Can you maybe give me the exact steps to reproduce the issue and your browser version?
Would also appreciate if you can check the Javascript console (right click -> inspect, then go to the console tab) and check if you can see any errors in there.

**Comment by pcboy** [comment]
Another thing to note is that only the points corresponding to the screws are used in the calculation. Respectively points 0,3,6,21,27,42,45,48 from left to right, top to bottom. If you try to change manually other points the results will be the same (but in real life you shouldn't get that different values between the screws, otherwise your bed would be totally fucked up). Now to be more precise I could take into account the intermediate values and average, not sure that would make a big difference in actual results in normal usage though, I can see problems arising from that, will try it to see. Also note the results are currently rounded to one decimal too.

**Comment by haarp** [comment]
> I can't reproduce this issue and fail to understand how that could happen. I must be missing some information.
> When you refresh the page the 2 input boxes should be reset and empty (beside the placeholder text).

Hmm, could be browser-specific then. I'm using Firefox 67.0 on Linux. When the page is refreshed, data entered into the upper field sticks around. It is not reset.

It doesn't seem to consistently stop updating, I've yet to reproduce itenoguh to provide steps. But it happens fairly often, and it does seem related to refreshing. I've confirmed it with two different datasets taken online (can't access the printer right now). They are

```
Recv: 0.21083 0.18148 0.15120 0.12000 0.08787 0.05481 0.02083
Recv: 0.21296 0.18017 0.14709 0.11370 0.08002 0.04604 0.01176
Recv: 0.20907 0.17400 0.13897 0.10398 0.06903 0.03413 -0.00074
Recv: 0.19917 0.16296 0.12685 0.09083 0.05491 0.01907 -0.01667
Recv: 0.18324 0.14706 0.11073 0.07426 0.03764 0.00088 -0.03602
Recv: 0.16130 0.12629 0.09061 0.05426 0.01724 -0.02044 -0.05880
Recv: 0.13333 0.10065 0.06648 0.03083 -0.00630 -0.04491 -0.08500
```

```
Recv: 0.256,0.170,0.140,0.535,0.183,0.159,0.054,0.197,0.105,0.105
Recv: 0.488,0.277,0.174,-0.049,0.125,0.020,0.027,0.070,-0.006,-0.006
Recv: 0.479,0.197,0.220,0.062,0.116,0.062,-0.053,0.169,0.038,0.038
Recv: 0.315,0.306,0.126,0.079,-0.096,-0.008,0.014,-0.105,0.011,0.127
Recv: 0.444,0.362,0.162,0.084,-0.160,-0.100,-0.074,-0.079,0.038,0.154
Recv: 0.506,0.293,0.195,0.274,0.093,-0.040,0.040,-0.083,-0.131,-0.131
Recv: 0.583,0.265,0.174,0.517,0.042,-0.021,-0.083,-0.094,-0.130,-0.130
Recv: 0.425,0.267,0.270,0.370,0.073,-0.125,-0.075,-0.057,-0.056,-0.056
Recv: 0.499,0.356,0.280,0.266,0.056,0.053,-0.021,0.120,-0.171,-0.171
Recv: 0.438,0.265,0.188,-0.154,0.141,0.005,-0.041,-0.117,-0.135,-0.135
```

I see no log in the browser console.

**Comment by pcboy** [comment]
I could reproduce the input box not cleared issue on Firefox. It's  now fixed.
I also added a "last updated at" text under the "Results" so you get visual feedback for the refresh.

I still could not reproduce what you mentioned with results not refreshing sadly. Results are supposed to be refreshed on every "keyUp" event on the first text field so that's hard to break..  
But again, note that only points  0,3,6,21,27,42,45,48 (i.e top left, top, top right etc) are used in the calculation, so if you change any other point you'll not see a different result in the bottom input.

**Comment by haarp** [comment]
Thank you for the quick work!

I can confirm that it clears on refresh in Firefox now. I also cannot get it to hang anymore.

The "last updated" is also a nice touch, although I would have preferred some sort of pulsing animation to make it more obvious :)

Cheers!
